django_app/urls.py
from django.urls import path
from django_app import views

app_name = 'django_app'
urlpatterns = [
    path('', views.home_view, name=''),
    path('index/', views.HomeView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('home_main/', views.home_main, name='home_main'),


    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_f, name='logout'),


    # path('post/ratings/', views.posts),
    path('post_list/', views.post_list, name='post_list'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/create/', views.post_comment_create, name='post_comment_create'),
    path('post/<int:pk>/comment/delete/', views.post_comment_delete, name='post_comment_delete'),
    path('post_create/', views.post_create, name='post_create'),

    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profileupdate, name='profile_update'),


    path('json_page/', views.json_page, name='json_page'),


    path('todo_list/', views.todo_list, name='todo_list'),
    path('todo_create/', views.todo_create, name='todo_create'),
    path('todo/<int:pk>/delete/', views.todo_delete, name='todo_delete'),
    path('test_controller/', views.controller_test, name='test_controller'),

    path('all_users/', views.all_users, name='all_users'),
    path('data_base/', views.database, name='database'),
    path('task/<int:pk>/delete/', views.task_delete, name='task_delete'),

    path('todo_list_pygt6/', views.todo_list_pygt6, name='todo_list_pygt6'),
]

django_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(
        verbose_name="Заголовок",
        default="",
        editable=True,
        blank=True,
        unique=True,
        db_index=True,

        max_length=150
    )
    description = models.TextField(
        verbose_name="Описание",
        default="",
        editable=True,
        blank=True
    )

    class Meta:
        app_label = 'django_app'
        ordering = ('id',)
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return f"Post: {self.title} {self.description[:30]} [{self.pk}]"


class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_images')
    first = models.ImageField(upload_to='profile_images', default='')
    second = models.ImageField(upload_to='profile_images', default='')
    third = models.ImageField(upload_to='profile_images', default='')
    forth = models.ImageField(upload_to='profile_images', default='')
    description = models.TextField(default='')
    city = models.TextField(default='')

    def __str__(self):
        return f'{self.user.username}'


class Todo(models.Model):
    title = models.CharField(
        verbose_name="Заголовок",
        default="",
        editable=True,
        blank=True,
        unique=False,
        db_index=True,
        null=True,

        max_length=150
    )
    description = models.TextField(
        verbose_name="Описание",
        default="",
        editable=True,
        blank=True,
        null=True,
    )

    class Meta:
        app_label = 'django_app'
        ordering = ('id',)
        verbose_name = 'Todo'
        verbose_name_plural = 'Todos'

    def __str__(self):
        return f"Todo: {self.title} {self.description[:30]} [{self.pk}]"

class Task(models.Model):
    title = models.CharField(
        verbose_name="Заголовок",
        default="",
        editable=True,
        blank=True,
        unique=False,
        db_index=True,
        null=True,

        max_length=150
    )
    description = models.TextField(
        verbose_name="Описание",
        default="",
        editable=True,
        blank=True,
        null=True,
    )

    class Meta:
        app_label = 'django_app'
        ordering = ('id',)
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return f"Task: {self.title} {self.description[:30]} [{self.pk}]"







django_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.apps import AppConfig
from .models import profile


class DjangoAppConfig(AppConfig):
    name = 'django_app'

    def ready(self):
        import django_app.signals


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['image', 'description', 'city', 'first', 'second', 'third', 'forth']

django_app/views.py
from django.contrib.auth import logout, authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User, Group
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django_app import models
from .forms import ProfileUpdateForm
import sys
import json
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtCore import Qt



# Create your views here.


class HomeView(View):  # TODO контроллер класс
    template_name = 'django_app/home.html'

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {}
        # return HttpResponse(content=b"<h1>Hello World</h1>")
        # return JsonResponse(data={"response": 'res'}, safe=True)
        return render(request, 'django_app/home.html', context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        context = {}
        # return HttpResponse(content=b"<h1>Hello World</h1>")
        # return JsonResponse(data={"response": 'res'}, safe=True)
        return render(request, 'django_app/home.html', context=context)


def home_view(request: HttpRequest) -> HttpResponse:  # TODO контроллер функция
    context = {}
    # return HttpResponse(content=b"<h1>Hello World</h1>")
    # return JsonResponse(data={"response": 'res'}, safe=True)
    return render(request, 'django_app/home.html', context=context)


def register(request: HttpRequest) -> HttpResponse:
    #

    if request.method == "GET":
        context = {}
        return render(request, 'django_app/register.html', context=context)
    elif request.method == "POST":

        # TODO получить с формы данные
        first_name = request.POST.get('first_name', "")
        last_name = request.POST.get('last_name', "")
        username = request.POST.get('username', None)
        password1 = request.POST.get('password1', "")
        password2 = request.POST.get('password2', "")

        if password1 and password1 != password2:
            raise Exception("пароли не совпадают!")
        if username and password1:
            User.objects.create(
                first_name=first_name,
                last_name=last_name,
                username=username,
                password=make_password(password1),
            )
            return redirect(reverse('django_app:login', args=()))
        else:
            raise Exception("данные не заполнены!")


def login(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":

        email = request.POST.get("email")
        password = request.POST.get("password")

        print(f"email: {email}")
        print(f"password: {password}")

        with open('static/temp/data.txt', 'w') as file:
            file.write(f"{email}\n")
            file.write(f"{password}\n")
    context = {}
    return render(request, 'django_app/login.html', context=context)


def post_list(request: HttpRequest) -> HttpResponse:
    posts = models.Post.objects.all()  # filter order_by
    context = {"posts": posts}
    return render(request, 'django_app/post_list.html', context=context)


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = models.Post.objects.get(id=pk)
    context = {"post": post}
    return render(request, 'django_app/post_detail.html', context=context)


def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    post = models.Post.objects.get(id=pk)
    post.delete()
    return redirect(reverse('django_app:post_list', args=()))


def post_pk_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "GET":
        # post_list = models.Post.objects.all()
        # print(f"post_list: {post_list}")
        # context = {"post_list": post_list}
        context = {}
        return render(request, 'django_app/post_detail.html', context=context)
    context = {}
    # return HttpResponse(content=b"<h1>Hello World</h1>")
    # return JsonResponse(data={"response": 'res'}, safe=True)
    return render(request, 'django_app/post_list.html', context=context)


def home_main(request: HttpRequest) -> HttpResponse:
    context = {}
    return render(request, 'django_app/home_main.html', context=context)


def post_comment_create(request: HttpRequest, pk: int) -> HttpResponse:
    if request.method == "POST":
        text = request.POST.get('text', None)
        post = models.Post.objects.get(id=pk)  # определить, к какой статье создали комментарий
        models.PostComment.objects.create(
            user=request.User,
            article=post,
            text=text,
            # date_time=timezone.now(), # у нас стоит default
        )
        return redirect(reverse('django_app:post_detail', args=(pk,)))


def post_comment_delete(request: HttpRequest, pk: int) -> HttpResponse:
    comment = models.PostComment.objects.get(id=pk)
    pk = comment.article.id
    comment.delete()
    return redirect(reverse('django_app:post_detail', args=(pk,)))


def post_create(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        context = {}
        return render(request, 'django_app/post_create.html', context=context)
    elif request.method == "POST":
        print("request: ", request)
        # print("request.data: ", request.data)
        print("request.POST: ", request.POST)
        print("request.GET: ", request.GET)
        print("request.META: ", request.META)

        title = request.POST.get('title', None)
        description = request.POST.get('description', "")
        post = models.Post.objects.create(
            title=title,
            description=description,
        )
        return redirect(reverse('django_app:post_list', args=()))


def logout_f(request: HttpRequest) -> HttpResponse:
    logout(request)
    return redirect(reverse('django_app:login', args=()))


def profile(request):
    return render(request, 'django_app/profile.html')


def profileupdate(request):
    if request.method == 'POST':
        pform = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if pform.is_valid:
            pform.save()
            return render(request, 'django_app/profile.html')
    else:
        pform = ProfileUpdateForm(instance=request.user.profile)
    return render(request, 'django_app/profileupdate.html', {'pform': pform})


def json_page(request):
    users = [{"name": f"Dimash ({x})", "age": x} for x in range(1, 8)]
    print(users)

    return JsonResponse({"Your information": users})


def todo_create(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        context = {}
        return render(request, 'django_app/todo_create.html', context=context)
    elif request.method == "POST":
        print("request: ", request)
        print("request.POST: ", request.POST)
        print("request.GET: ", request.GET)
        print("request.META: ", request.META)

        title = request.POST.get('title', "")
        description = request.POST.get('description', "")
        todo = models.Todo.objects.create(
            title=title,
            description=description,
        )
        return redirect(reverse('django_app:todo_list', args=()))

class CustomPaginator:
    @staticmethod
    def paginate(object_list: any, per_page=5, page_number=1):
        paginator_instance = Paginator(object_list=object_list, per_page=per_page)
        try:
            page = paginator_instance.page(number=page_number)
        except PageNotAnInteger:
            page = paginator_instance.page(number=1)
        except EmptyPage:
            page = paginator_instance.page(number=paginator_instance.num_pages)
        return page


def todo_list(request: HttpRequest) -> HttpResponse:
    todos = models.Todo.objects.all()

    selected_page_number = request.GET.get('page', 1)
    selected_limit_objects_per_page = request.GET.get('limit', 3)
    if request.method == "POST":
        selected_page_number = 1
        selected_limit_objects_per_page = 9999

        search_by_title = request.POST.get('search', None)
        if search_by_title is not None:
            todos = todos.filter(title__contains=str(search_by_title))

    page = CustomPaginator.paginate(
        object_list=todos, per_page=selected_limit_objects_per_page, page_number=selected_page_number
    )

    context = {"page": page}
    return render(request, 'django_app/todo_list.html', context=context)


def todo_delete(request: HttpRequest, pk: int) -> HttpResponse:
    todo = models.Todo.objects.get(id=pk)
    todo.delete()
    return redirect(reverse('django_app:todo_list', args=()))


def controller_test(request: HttpRequest) -> HttpResponse:
    context = {}
    return render(request, 'django_app/testcontroller.html', context=context)


def all_users(request):
    users = User.objects.all()

    selected_page_number = request.GET.get('page', 1)
    selected_limit_objects_per_page = request.GET.get('limit', 3)
    if request.method == "POST":
        selected_page_number = 1
        selected_limit_objects_per_page = 9999

        search_by_user = request.POST.get('search', None)
        if search_by_user is not None:
            users = users.filter(username__contains=str(search_by_user))

        # TODO просто расскаментируйте внизу и фильтр будет работать, не знаю в чем проблема,
        #  но они работают только по отдельности

        # filter_by_user = request.POST.get('filter', None)
        # if filter_by_user is not None:
        #     users = users.filter(username=filter_by_user)

    page = CustomPaginator.paginate(

templates/django_app/all_users.html
{% load static %}

{% block main %}
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    {% block prestyles %}{% endblock prestyles %}
    <link href="signin.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/fontawesome/css/all.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/css/my2.css" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/my2.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li style="margin-right: 15px;">
                        <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; z-index: 1; border-radius: 100%;">
          {% if user.is_authenticated %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2">Profile({{ user.username}})</a>
        {% else %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>
        {% endif %}
          </li>
        <li class="nav-item">
        <a href="{% url 'django_app:home_main' %}" class="btn btn-outline-primary" type="submit">Home</a>
        <a href="{% url 'django_app:post_create' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">Create new post</a>
        <a href="{% url 'django_app:todo_create' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">Create new todo</a>
            <a href="{% url 'django_app:post_list' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">All posts</a>
            <a href="{% url 'django_app:todo_list' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">All todos</a>
            <a href="{% url 'django_app:all_users' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">All users</a>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <div class="text-end">
          {% if user.is_authenticated %}
              <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>
          {% else %}
              <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>
          {% endif %}
          </div>
      </form>
    </div>
  </div>
</nav>
<h1 align="center">All users</h1>
 <a href="{% url 'django_app:all_users' %}" class="btn btn-success" type="submit" style="margin-left: 15px; margin-bottom: 15px;">All users</a>
<form action="{% url 'django_app:all_users' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <div class="input-group">
<input type="search" class="form-control p-3 w-50" placeholder="Search by users" name="search">
        <button class="btn btn-lg btn-primary" type="submit">Search</button>
        <select class="form-select" required aria-label="Default select example" name="filter">
  <option selected>Select user</option>
            {% for i in users %}
                <option value="{{ i.username }}">{{ i.username }}</option>
            {% endfor %}
</select>
        <button class="btn btn-lg btn-primary" type="submit">Search</button>
    </div>
  </form>
    <div class="container container-fluid">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for user in page %}
            <div class="col">
              <div class="card shadow-sm" style="border-radius: 30px;">
                <div class="card-header" align="center">{{ user.username }}</div>
                    <div class="btn-group">
                    <div style="margin-left: 300px; border: 1px solid #E1C16E; text-align: center;">
                    {{ forloop.counter }}
                  </div>
                </div>
              </div>

            </div>


        {% endfor %}
      </div>
    </div>
{% include 'components/pagination.html' %}
{% endblock main %}

templates/django_app/home.html
{% extends "components/base.html" %}

{% block title %}Twitter Home{% endblock title %}
{% block main %}

{% endblock main %}

templates/django_app/home_main.html
{% include 'components/main.html' %}

templates/django_app/post_create.html
{% block main %}
    <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    {% block prestyles %}{% endblock prestyles %}
    <link href="signin.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/fontawesome/css/all.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/css/my.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
      <li style="margin-right: 15px;">
                                  <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; z-index: 1; border-radius: 100%;">
          {% if user.is_authenticated %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2">Profile({{ user.username}})</a>
        {% else %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>
        {% endif %}
          </li>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
        </li>
        <a href="{% url 'django_app:home_main' %}" class="btn btn-outline-primary" type="submit" style="margin-right: 8px;">Home</a>
        <a href="{% url 'django_app:post_list' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">All posts</a>
      </ul>
      <form class="d-flex">
        <div class="text-end">
          {% if user.is_authenticated %}
              <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>
          {% else %}
              <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>
          {% endif %}
          </div>
      </form>
    </div>
  </div>
</nav>
    <div class="container container-fluid">
<i class="fa-solid fa-user"></i>
        <i class="fa-solid fa-comment"></i>
        <main class="form-signin">
  <form action="{% url 'django_app:post_create' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">Add your new tweet!</h1>
        Title:
      <input type="text" class="form-control m-3" placeholder="Enter here your title" name="title">
      Description:
      <textarea type="text" class="form-control m-3" rows="5" name="description" placeholder="Enter here your discription"></textarea>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Tweet</button>
  </form>
</main>


    </div>
    <div>
      <img src="https://i.gifer.com/7S8u.gif" >
    </div>

{% endblock main %}

templates/django_app/todo_create_pygt6.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <small class="text-muted">
        <a href="{% url 'django_app:todo_list_pygt6' %}" class="text-decoration-none btn"><i class="fa-solid fa-trash-can text-danger">TodoList</i></a>
    </small>
</body>
</html>

templates/django_app/todo_list.html
{% load static %}

{% block main %}
        <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">
    {% block prestyles %}{% endblock prestyles %}
    <link href="signin.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/fontawesome/css/all.css" rel="stylesheet" crossorigin="anonymous">
    <link href="/css/my2.css" rel="stylesheet" crossorigin="anonymous">
    <link href="{% static 'css/my2.css' %}" rel="stylesheet" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li style="margin-right: 15px;">
                        <img src="{{ user.profile.image.url }}" alt="Generic placeholder image" class="img-fluid " style="width: 50px; z-index: 1; border-radius: 100%;">
          {% if user.is_authenticated %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-Success me-2">Profile({{ user.username}})</a>
        {% else %}
            <a href="{% url 'django_app:profile' %}" type="button" class="btn btn-outline-primary me-2">Profile(anonymous)</a>
        {% endif %}
          </li>
        <li class="nav-item">
        <a href="{% url 'django_app:home_main' %}" class="btn btn-outline-primary" type="submit">Home</a>
        <a href="{% url 'django_app:post_create' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">Create new post</a>
        <a href="{% url 'django_app:todo_create' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">Create new todo</a>
            <a href="{% url 'django_app:todo_list' %}" class="btn btn-outline-primary" type="submit" style="margin-left: 15px;">All todos</a>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <div class="text-end">
          {% if user.is_authenticated %}
              <a href="{% url 'django_app:logout' %}" type="button" class="btn btn-outline-danger me-2">Logout</a>
          {% else %}
              <a href="{% url 'django_app:login' %}" type="button" class="btn btn-outline-primary me-2">Login(anonymous)</a>
          {% endif %}
          </div>
      </form>
    </div>
  </div>
</nav>
<h1 align="center">All todos</h1>
<form action="{% url 'django_app:todo_list' %}"
    method="POST"
    enctype="multipart/form-data"
  >
      {% csrf_token %}
    <div class="input-group">
<input type="search" class="form-control p-3 w-50" placeholder="Search by names" name="search">
        <button class="btn btn-lg btn-primary" type="submit">Search</button>
    </div>
  </form>
    <div class="container container-fluid">

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for todo in page %}
            <div class="col">
              <div class="card shadow-sm" style="border-radius: 30px;">
                <div class="card-header" align="center">{{ todo.title }}</div>
                <div class="card-body">
                  <p class="card-text">{{ todo.description }}</p>
                  <div class="d-flex justify-content-between align-items-center" >
                    <div class="btn-group">
                      <a href="#" type="button" class="btn btn-sm btn-outline-secondary">Details...</a>
                      <a href="#" type="button" class="btn btn-sm btn-outline-secondary">Edit</a>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                    <small class="text-muted">
                        <a href="{% url 'django_app:todo_delete' todo.id %}" class="text-decoration-none btn"><i class="fa-solid fa-trash-can text-danger">Delete</i></a>
                    </small>
                    <div style="margin-left: 300px; border: 1px solid #E1C16E; text-align: center;">
                    {{ forloop.counter }}
                  </div>
                </div>
              </div>

            </div>


        {% endfor %}
      </div>
    </div>
{% include 'components/pagination.html' %}
{% endblock main %}